### ISSUE TITLE
Weekday of returned time.Time

### ISSUE THREAD

**Issue by glaslos** [chneau/openhours#3]
In my application, I would like to turn the parse opening hours into a displayable string. Something like this:
```
Monday 08:00 - 12:00
Tuesday 08:00 - 12:00
```
Unfortunately [here](https://github.com/Vivino/openhours/blob/c2489c295da6ac7980c7a9c104e15c4bf547a660/openhours.go#L21-L23) the created date/time object for Monday is 2017-01-01 which is actually a Sunday.

One solution would be changing the year to e.g. 2004 for which 2004-01-01 is a Monday. But there is also an issue with the day mapping since Sunday is `0` [here](https://github.com/Vivino/openhours/blob/c2489c295da6ac7980c7a9c104e15c4bf547a660/openhours.go#L12).

**Comment by chneau** [comment]
A quick dirty implementation would be:

```go
// String returns the string representation of the open hours
// in this format:
// Monday 08:00 - 12:00
// Tuesday 08:00 - 12:00
func (o OpenHours) String() string {
	if len(o) == 0 {
		return ""
	}
	str := ""
	for i := 0; i < len(o); i += 2 {
		str += (o[i].Weekday() + 1).String() + " " + o[i].Format("15:04") + " - " + o[i+1].Format("15:04") + "\n"
	}
	return str[:len(str)-1]
}
```
the start of the week could be controlled by a parameter if needed but I'm happy with Monday as first as I am more familiar with it.
with a test a quick test
```go

func TestOpenHours_String(t *testing.T) {
	tests := []struct {
		name string
		o    OpenHours
		want string
	}{
		{"empty", OpenHours{}, ""},
		{"simple", NewMust("mo 10:00-15:00", l), "Monday 10:00 - 15:00"},
		{"two", NewMust("mo 10:00-15:00;fr 08:00-14:00", l), "Monday 10:00 - 15:00\nFriday 08:00 - 14:00"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.o.String(); got != tt.want {
				t.Errorf("OpenHours.String() = %v, want %v", got, tt.want)
			}
		})
	}
}
```
